Use snapkit to layout datePickerView
cuappdev/ithaca-transit-ios pull request #256
Opened 2019-08-23 20:56 UTC by Omarrasheed

2019-08-23 21:11 UTC, kevinchan159 requested changes
nice just left few comments

2019-08-23 21:11 UTC, kevinchan159 commented on TCAT/Views/DatePickerView.swift
> +            make.size.equalTo(CGSize(width: 60, height: buttonHeight))
move numbers into constants at top of function

2019-08-23 21:11 UTC, kevinchan159 commented on TCAT/Views/DatePickerView.swift
> +            leaveNowSegmentedControl.selectedSegmentIndex = typeToSegmentControlElements[.leaveNow]!.index
can we unwrap instead of `!`

2019-08-23 21:11 UTC, kevinchan159 commented on TCAT/Views/DatePickerView.swift
> +        if timeTypeSegmentedControl.selectedSegmentIndex == typeToSegmentControlElements[.arriveBy]!.index {
unwrap instead of `!`

2019-08-23 21:11 UTC, kevinchan159 commented on TCAT/Views/DatePickerView.swift
> +        for i in options.indices {
pref to use `forEach`

2019-08-23 22:25 UTC, Omarrasheed commented
Updated! @kevinchan159

2019-08-23 23:15 UTC, kevinchan159 approved these changes
NOICE, just remember to squash before merging

2019-08-24 00:29 UTC, young-k approved these changes
Fix & feel free to merge afterwards

2019-08-24 00:29 UTC, young-k commented on TCAT/Views/DatePickerView.swift
> +    // MARK: Segement Controls
You spelled "segment" wrong!

2019-08-24 01:14 UTC, merged